[workspace]
members = ["frand-property-macro", "frand-property-slint"]
package.version = "0.2.4"
package.edition = "2024"
package.authors = ["frand-nano <frand.nano@gmail.com>"]

[package]
name = "frand-property"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = [ "slint" ]
slint = ["dep:slint"]

[dependencies]
frand-property-macro = { path = "frand-property-macro" }

slint = { version = "1.14", optional = true }

tokio = { version = "1.48", features = ["rt-multi-thread", "macros", "sync"] }
arraystring = "0.3"