[package]
name = "frand-property-build"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
walkdir = "2.3"
anyhow = "1.0"
heck = "0.5.0"
